### ISSUE TITLE
test subcommand doesn't actually test

### ISSUE THREAD

**Issue by GoldsteinE** [tfpk/macrokata#15]
It would be nice to auto-compare AST, since doing it manually is quite painful for larger examples.

**Comment by tfpk** [comment]
Completely agreed -- I didn't put effort into it because releasing this project was on a deadline; but it's something I'd love to add.

Next on my list is to add some improvements to cargo-expand (well, possibly totally rewrite it to not depend on nightly). But I don't think that work blocks doing this.

If someone is interested in giving this a shot, I'd be happy to mentor them/give a hand with design/whatever is needed.

If this isn't fixed by the time I've improved cargo-expand; I'll put some more effort into this.

**Comment by tfpk** [comment]
In #20  we added diffing. I'll be keen for feedback on whether this is enough to solve this issue -- if it's not; I'd ask people to open a new issue where we can discuss this further.

In the meantime, closing this issue as fixed.
