### ISSUE TITLE
capturing `Copy` values

### ISSUE THREAD

**Issue by skaunov** [tfpk/macrokata#52]
I wonder if `11_macro_recursion` needs also to mention that capturing by value respects `Copy` `trait`, since it's a little bit puzzling (at least for me) that `print_curried_argument()` get ownership of `$argident`, and then it's used in following closures. (While solving I used borrow, and your beautiful `test`ing system showed me everything.) X)

IIUC `Copy` [explains] this nuance. And I don't really know if it deserves to be mentioned in the exercise, or not.
[explains]: https://github.com/rust-lang/rust-by-example/blob/31961fe22521a779070a44a8f30a2b00a20b6212/src/fn/closures/capture.md?plain=1#L71

**Comment by tfpk** [comment]
Hi!

So yes, Copy does explain this nuance; but I'm not sure what the best options are. We could:
 - Explain why `Copy` makes this code work.
 - Require that the argument is Copy, which makes it more obvious that Copy is the reason this works.
 - Use a borrow, to make the code more understandable.

I'm hesitant to explain Copy here, because we'll have many users who do know about Copy; and re-explaining it here might cause confusion ("they're explaining copy here, is copy affected by macro recursion???"). It's also somewhat off-topic for this guide.

Using borrow is almost certainly the "rustiest" solution (as evidenced by the fact that you reached for it); but it'll require a change to the exercise answer (which I can do, but I'm just careful about). requiring `Copy` is a middle way, but might be too un-idiomatic to justify it.

I'll sleep on this; and if you've got any thoughts I'd love to hear them.

**Comment by skaunov** [comment]
Totally agree! I can add only couple of things atm.

I was thinking if adding a non-`Copy` type to the exercise would show this. But I'm afraid it would broaden the focus of the exercise, while it's already not that simple/easy.

The second point is that I indeed like how Rust by example presented the thing (linked earlier). They don't explain `Copy` in this topic, but just point out that capturing use it too. As a an option to consider: maybe there's more appropriate place to mention the thing in an earlier exercise?

**Comment by tfpk** [comment]
Realised I never resolved this, sorry: I've pushed an additional sentence to the chapter explaining that the `print_curried_argument` takes a value which you can assume will be copy. Basically as you suggested -- thanks :)

Hopefully that's enough for now; though if anyone happens upon this issue and disagrees I'm very happy to consider changing the exercise further.
