### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by skaunov** [tfpk/macrokata#55]
@tfpk , while creating this (exercise) book did you ever thought to add a chapter on Testing ?

https://stackoverflow.com/questions/61171437/is-there-a-way-to-test-macros-in-rust/61171504#comment134610126_61171504

**Comment by tfpk** [comment]
No it's not something I'd considered. I'm absolutely open to the idea; though I don't think it's well established or widely used. Therefore, it might turn into a "how to use this particular tool", which may be quite opinionated; as opposed to "this is the way everyone does it" which is why I feel comfortable using things like a Rust LSP.

Closing this for neatness, but feel free to open an issue or a draft PR if you have a specific way of writing it you think would be valuable.

**Comment by skaunov** [comment]
Do you mean tools like `fmt` and `clippy` speaking of Rust LSP?

**Comment by tfpk** [comment]
Yeah, they're very standard. Whereas, I don't think there's a standard way to test macros (apart from unit testing, of course).
